[versions]
agp = "8.4.2"
kotlin = "1.9.10"
xposed = "82"

[libraries]
xposed = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

